spring:
    jpa:
      hibernate:
        ddl-auto: update
    datasource:
      url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
      username: root
      password: root
    jackson:
      default-property-inclusion: non_null

jwt:
    secret: B?E(H+MbQeThWmZq4t7w!z%C*F-J@NcRfUjXn2r5u8x/A?D(G+KbPdSgVkYp3s6v
    expiration: 999999
